project:
  type: website
  output-dir: docs

website:
  title: "Abraham Ayiah Yankson"
  navbar:
    background: success
    search: true
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: CV.qmd
        text: "{{< fa user-tie >}} CV"
      
    right: 
      - href: Contact.qmd
        text: "{{< fa envelope >}} Contact"
        
      - href: https://twitter.com/AbrahamAyiah
        icon: twitter
      
      - href: https://abrahamayiahyankson.github.io/My-Personal-Website/
        icon: github


        
        
    

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

