---
title: "Curriculum Vitae"
---

## Contact Information

{{< fa envelope >}} [aayankson@mun.ca](mailto:aayankson@mun.ca)

                                      Department of Economics
                                      
                                      Memorial University of Newfoundland
                                      
                                      215A Empire Avenue
                                      
                                      St.John's, NL, Canada
                                      
                                      A1C 3H3
                                      


## Academic Profiles and Website

## Education

- MA Economics (2023), Memorial University of Newfoundland;

- BA Economics (2020), University of Ghana, Legon.

- General Arts (2016), Ghana Senior High Technical School, Takoradi

## Current Positions

- Graduate Teaching and Research Assistant (2024), Department of Economics, Memorial University of Newfoundland.

- Founder and President (2019-), Care for Humanity Initiative Foundation Ghana (CHIF-GHANA).

## Previous Positions

- Teaching Assistant (2022), Department of Economics, University of Ghana, Legon.

- Research Assistant (2021), Ghana Statistical Service, Accra.

- Field Supervisor and Monitor (2021), 2021 Population and Housing Census, Ghana Statistical Service.

## Research Interest and Specialization

- Applied Micro-econometrics

- Labour Economics

- Monetary Economics

## Skills
- Stata 

- latex

- R and Quarto

- Data Analytics and Economic Modelling.
